// This code was generated by a vsSolutionBuildEvent. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
namespace net.r_eg.MoConTool
{
    using System;

    public struct MoConToolVersion
    {
        public static readonly Version number = new Version(S_NUM_REV);

        public const string S_NUM = "1.0.0";
        public const string S_REV = "9046";

        public const string S_NUM_REV = S_NUM + "." + S_REV;

        public const string BRANCH_SHA1 = "b6e1870";
        public const string BRANCH_NAME = "master";
        public const string BRANCH_REVC = "12";

        internal const string S_INFO        = S_NUM_REV + " [ " + BRANCH_SHA1 + " ]";
        internal const string S_INFO_FULL   = S_INFO + " /'" + BRANCH_NAME + "':" + BRANCH_REVC;
    }
}